plugins {
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'eclipse'
    id 'maven-publish'
}


version = '1.0.2'
group = 'com.miku.coordinateselector'


base {
    archivesName = 'coordinate_selector'
}


java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}


minecraft {

    mappings channel: 'official',
             version: '1.20.1'


    runs {

        client {

            workingDirectory project.file('run')


            property 'forge.logging.markers',
                    'REGISTRIES'


            property 'forge.logging.console.level',
                    'debug'


            mods {

                coordinate_selector {

                    source sourceSets.main

                }

            }

        }


        server {

            workingDirectory project.file('run')


            mods {

                coordinate_selector {

                    source sourceSets.main

                }

            }

        }

    }

}



repositories {

    flatDir {

        dirs 'libs'

    }

}



dependencies {


    minecraft 'net.minecraftforge:forge:1.20.1-47.1.0'


    // Wormhole 1.1.17
    implementation files(
            'libs/wormhole-1.1.17-forge-mc1.20.1.jar'
    )


    // Wormhole 前置库
    implementation files(
            'libs/supermartijn642corelib-1.1.17-forge-mc1.20.1.jar'
    )


}



tasks.named('jar', Jar).configure {


    manifest {

        attributes([

                'Specification-Title': 'coordinate_selector',

                'Specification-Version': '1',

                'Implementation-Title': project.name,

                'Implementation-Version': project.jar.archiveVersion

        ])

    }

}



jar.finalizedBy('reobfJar')
